# Generated by Django 2.2.19 on 2023-02-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230212_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='adress_slug',
        ),
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
